---
apiVersion: v1
kind: Service
metadata:
  name: ipserver
spec:
  type: LoadBalancer
  selector:
    app: ipserver
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ipserver
  template:
    metadata:
      labels:
        app: ipserver
    spec:
      containers:
      - name: ipserver
        image: torbencarstens/ipserver{{TAG}}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
